import 'package:flutter/material.dart';
import 'package:meal_app0/models/meal.dart';
import 'models/category.dart';

List DUMMY_CATEGORIES = [
  Category1(
    id: 'c1',
    title: 'Italian',
    color: Colors.red,
  ),
  Category1(
    id: 'c2',
    title: 'Quick & Easy',
    color: Colors.purple,
  ),
  Category1(
    id: 'c3',
    title: 'Hamburgers',
    color: Colors.orange,
  ),
  Category1(
    id: 'c4',
    title: 'German',
    color: Colors.amber,
  ),
  Category1(
    id: 'c6',
    title: 'Light & Lovely',
    color: Colors.blue,
  ),
  Category1(
    id: 'c6',
    title: 'Exotic',
    color: Colors.green,
  ),
  Category1(
    id: 'c7',
    title: 'Breakfast',
    color: Colors.lightBlue,
  ),
  Category1(
    id: 'c8',
    title: 'Asian',
    color: Colors.lightGreen,
  ),
  Category1(
    id: 'c9',
    title: 'French',
    color: Colors.lightGreenAccent,
  ),
  Category1(
    id: 'c10',
    title: 'Italian',
    color: Colors.red,
  ),
];

List DUMMY_MEAL = [
  Meal(
      id: 'm1',
      categories: ['c1','c2'],
      title: 'Spaghetti with Tomato Sauace',
      imageUrl:"https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      // 'https://upload.wikimedia.org/wikipedia/common/thumb/2/20/Spaghetti_Bolognese_mit_p',
      ingredients:[
        '4 Tomatoes ',
        '1 Tablespoon of Olive Oil',
        '1 Onion ',
        '250g Spaghetti ',
        'Spices ',
        'Chees (optional)'

      ] ,
      steps: [
        'Cut the tomatoes and the onion into small pieces ',
        'Boil some water -add salt to it once it boilsb',
        'Put the spaghetti into the boiling water - they should be in done in about 10'
        'In the meantime heaten up some olive oil and add the cut onion ',
        'After 2 minutes ,add the tomato pieces ,salt pepper and your other spices ',
        'The sauce  will be done once the spaghetti are. ',
        'Feel free to add some cheese on top of the finished dish.'
      ],
      duration: 20,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: true,
      isVegan: true,
      isVegetarian: true),
  Meal(
      id: 'm2',
      categories: ['c3','c1'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm3',
      categories: ['c3'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'one ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm4',
      categories: ['c4'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm5',
      categories: ['c5','c4'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm6',
      categories: ['c6','c2'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm7',
      categories: ['c7'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm8',
      categories: ['c8'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm9',
      categories: ['c9'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
  Meal(
      id: 'm10',
      categories: ['c10'],
      title: 'Toast Hawaii',
      imageUrl: "https://cdn.pixabay.com/photo/2018/07/11/21/51/toast-3532016_1280.jpg",
      ingredients:[
        '1 Slice White Bread ',
        '1 Slice ham',
        '1 Slice Pineapple  ',
        '1-2 Slice of chees ',
        'Butter ',
      ] ,
      steps: [
        'Butter one side of the white bread  ',
        'Layer ham the pineapple and chees on the white bread',
        'Bake the toast  for round about 10 minutes in the oven at 200"c',
      ],
      duration: 10,
      complexity: Complexity.Simple,
      affordebility: Affordebility.Affordeble,
      isGlutenFree: false,
      isLactoseFree: false,
      isVegan: false,
      isVegetarian: false),
];
